### ISSUE TITLE
weird bug when holding

### ISSUE THREAD

**Issue by Zomore1** [hiimjustin000/EveryKeyJumps#1]
![image](https://github.com/hiimjustin000/EveryKeyJumps/assets/171040049/8dad0c28-20d2-480b-8b02-83eef8a6864f)

u can hold a key to click in every single frame possible making spam 100 times easier like i preview in the image
kinda like when u hold wasd to move a obj faster in the editor

**Comment by hiimjasmine00** [comment]
This is a bug that someone else discovered. I found a way to reproduce it, I just need someone to find a way to fix it.

**Comment by hiimjasmine00** [comment]
Fixed in v1.0.2
